{% set name = "winfiletime" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/winfiletime-{{ version }}.tar.gz
  sha256: c7c0337ac9ca1af982f623433f93dcbdf5d950eebdf92cd822093311650978ba
  patches:
    # Version 2.0 includes a superfluous import that prevents the module from being imported. Patch it until a new version is released
    - 0001-utc.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7.0,<4.0.0

test:
  imports:
    - winfiletime
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jleclanche/winfiletime
  summary: Win32 Filetime / Datetime conversion functions
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - n-elie
